{% set name = "pyiron_base" %}
{% set version = "0.12.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyiron_base-{{ version }}.tar.gz
  sha256: bb1c7d1377de54bda3cad02b24f8897a62306a329a98165d5a3425e630974efd

build:
  entry_points:
    - pyiron=pyiron_base.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - cloudpickle
    - gitpython
    - h5io_browser
    - h5py
    - jinja2
    - monty
    - numpy
    - pandas
    - pint
    - psutil
    - pyfileindex
    - pysqa
    - sqlalchemy
    - pytables
    - tqdm
    - traitlets
    - pyiron_dataclasses
    - pyiron_snippets
    - versioneer
    - toml
    - setuptools
  run:
    - pyiron_dataclasses ==0.0.1
    - executorlib >=0.1.0,<=1.2.0
    - python >={{ python_min }},<3.14
    - cloudpickle >=2.0.0,<=3.1.1
    - h5io_browser >=0.0.14,<=0.1.10
    - h5py >=3.6.0,<=3.13.0
    - monty >=2025.1.3,<=2025.3.3
    - numpy >=1.23.5,<=2.2.4
    - pandas >=2.0.0,<=2.2.3
    - psutil >=5.8.0,<=7.0.0
    - pyfileindex >=0.0.16,<=0.0.35
    - pyiron_snippets >=0.1.3,<=0.2.0
    - pysqa >=0.1.12,<=0.2.4
    - sqlalchemy >=2.0.22,<=2.0.40
    - pytables >=3.6.1,<=3.10.2
    - tqdm >=4.44.0,<=4.67.1
    - traitlets >=5.1.1,<=5.14.3

test:
  imports:
    - pyiron_base
  commands:
    - pip check
    - pyiron --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pyiron/pyiron_base
  summary: pyiron_base - an integrated development environment (IDE) for computational science.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - niklassiemer
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
