{% set name = "pyiron_base" %}
{% set version = "0.10.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyiron_base-{{ version }}.tar.gz
  sha256: e2e70df752533acc38a18107b2263937df8c403b2bb82e6ae08cc0b2893de3d8

build:
  entry_points:
    - pyiron=pyiron_base.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.13
    - pip
    - setuptools
    - cloudpickle
    - gitpython
    - h5io_browser
    - h5py
    - jinja2
    - monty
    - numpy
    - pandas
    - pint
    - psutil
    - pyfileindex
    - pysqa
    - sqlalchemy
    - pytables
    - tqdm
    - traitlets
    - pyiron_dataclasses
    - pyiron_snippets
    - versioneer
    - toml
    - setuptools
  run:
    - pyiron_dataclasses ==0.0.1
    - executorlib >=0.0.1,<=0.0.5
    - python >=3.8,<3.13
    - cloudpickle >=2.0.0,<=3.1.0
    - h5io_browser >=0.0.14,<=0.1.4
    - h5py >=3.6.0,<=3.12.1
    - monty >=2021.3.3,<=2024.10.21
    - numpy >=1.23.5,<=1.26.4
    - pandas >=2.0.0,<=2.2.3
    - psutil >=5.8.0,<=6.1.0
    - pyfileindex >=0.0.16,<=0.0.31
    - pyiron_snippets >=0.1.3,<=0.1.4
    - pysqa >=0.1.12,<=0.2.2
    - sqlalchemy >=2.0.22,<=2.0.36
    - pytables >=3.6.1,<=3.10.1
    - tqdm >=4.44.0,<=4.67.0
    - traitlets >=5.1.1,<=5.14.3

test:
  imports:
    - pyiron_base
  commands:
    - pip check
    - pyiron --help
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_base
  summary: pyiron_base - an integrated development environment (IDE) for computational science.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - niklassiemer
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
