{% set name = "pyiron_base" %}
{% set version = "0.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyiron_base-{{ version }}.tar.gz
  sha256: 1fdb933b24d97dbba593496edbb0ccd0b7a48f32e42d5d2210e2ead97bcf188b

build:
  entry_points:
    - pyiron=pyiron_base.cli:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8,<3.13
    - pip
    - cloudpickle
    - gitpython
    - h5io_browser
    - h5py
    - jinja2
    - monty
    - numpy
    - pandas
    - pint
    - psutil
    - pyfileindex
    - pysqa
    - sqlalchemy
    - pytables
    - tqdm
    - traitlets
    - pyiron_snippets
    - versioneer
    - toml
  run:
    - executorlib ==0.0.1
    - python >=3.8,<3.13
    - cloudpickle >=2.0.0,<=3.0.0
    - gitpython >=3.1.23,<=3.1.43
    - h5io_browser >=0.0.14,<=0.0.15
    - h5py >=3.6.0,<=3.11.0
    - jinja2 >=2.11.3,<=3.1.4
    - monty >=2021.3.3,<=2024.7.12
    - numpy >=1.23.5,<=1.26.4
    - pandas >=2.0.0,<=2.2.2
    - pint >=0.18,<=0.24.3
    - psutil >=5.8.0,<=6.0.0
    - pyfileindex >=0.0.16,<=0.0.25
    - pyiron_snippets >=0.1.1,<=0.1.2
    - pysqa >=0.1.12,<=0.1.21
    - sqlalchemy >=2.0.22,<=2.0.31
    - pytables >=3.6.1,<=3.9.2
    - tqdm >=4.44.0,<=4.66.4
    - traitlets >=5.1.1,<=5.14.3

test:
  imports:
    - pyiron_base
  commands:
    - pip check
    - pyiron --help
  requires:
    - pip

about:
  home: https://github.com/pyiron/pyiron_base
  summary: pyiron_base - an integrated development environment (IDE) for computational science.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - niklassiemer
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
