schema_version: 1

context:
  name: pyiron_base
  version: "0.15.1"
  python_min: '3.11'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pyiron_base-${{ version }}.tar.gz
  sha256: 62806100d8a70b82a34b4607dc85815a2c1d2a9e2d2eb34d3607040c0f48c6dc

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - pyiron=pyiron_base.cli:main

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
    - cloudpickle
    - gitpython
    - h5io_browser
    - h5py
    - jinja2
    - monty
    - numpy
    - pandas
    - pint
    - psutil
    - pyfileindex
    - pysqa
    - sqlalchemy
    - pytables
    - tqdm
    - traitlets
    - pyiron_dataclasses
    - pyiron_snippets
    - hatchling
    - hatch-vcs
  run:
    - python >=${{ python_min }},<3.14
    - cloudpickle >=2.2.1,<=3.1.1
    - executorlib >=0.1.0,<=1.7.1
    - h5io_browser >=0.0.14,<=0.2.1
    - h5py >=3.11.0,<=3.14.0
    - numpy >=1.26.0,<=2.3.2
    - monty >=2025.1.3,<=2025.3.3
    - pandas >=2.0.0,<=2.3.2
    - psutil >=5.9.3,<=7.1.0
    - pyfileindex >=0.0.16,<=0.0.40
    - pyiron_dataclasses ==0.0.4
    - pyiron_snippets >=0.1.3,<=0.2.0
    - pysqa >=0.1.12,<=0.3.1
    - sqlalchemy >=2.0.22,<=2.0.43
    - pytables =3.10.2
    - tqdm >=4.44.0,<=4.67.1
    - traitlets >=5.1.1,<=5.14.3

tests:
  - python:
      imports:
        - pyiron_base
      pip_check: true
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pyiron --help

about:
  summary: pyiron_base - an integrated development environment (IDE) for computational science.
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/pyiron/pyiron_base

extra:
  recipe-maintainers:
    - niklassiemer
    - srmnitc
    - pyiron-runner
    - jan-janssen
    - pmrv
